import {UserCache, thenSequence} from '../lib';

let UC = new UserCache([
    'Charlie Chaplin',
    'Don Johnson',
    'Mel Gibson',
    'Vin Diisel',
    'Ron Viislei',
    'Harry Potter',
], __filename, jasmine);

beforeAll(() => UC.setup());
afterAll(() => UC.cleanup());

let create_conv_result = {
    "header": {
      "admins": [
        "<account:Charlie Chaplin>",
      ],
      "autojoin_url": "<autojoin:autoManagedConvTopic>",
      "begin_message_nr": 1,
      "bw_message_nr": 1,
      "can_post": true,
      "cmail": "<cmail:autoManagedConvTopic>",
      "conversation_id": "<conv:autoManagedConvTopic>",
      "creator_id": "<account:Charlie Chaplin>",
      "default_members": [],
      "export_files": [],
      "export_progress": "1",
      "fw_message_nr": 1,
      "guests": [],
      "has_email_subject": false,
      "has_pinboard": false,
      "has_task_archive": false,
      "has_taskboard": false,
      "inbox_message_nr": 1,
      "inbox_time": "...",
      "is_automute": false,
      "is_full": true,
      "is_init": true,
      "is_list": false,
      "is_managed": true,
      "is_mark_unread": false,
      "is_premium": false,
      "is_tiny": false,
      "join_message_nr": 1,
      "label_ids": [],
      "last_inbox_nr": 0,
      "last_message_nr": 1,
      "last_message_time": "...",
      "leavers": [],
      "members": [
        "<account:Charlie Chaplin>",
        "<account:Don Johnson>",
        "<account:Mel Gibson>",
      ],
      "mk_alert_level": "default",
      "mk_conv_type": "cct_default",
      "mk_init_mode": "ic_full",
      "mk_rec_type": "conv",
      "organisation_id": "<org:autoManagedConvOrgName>",
      "passive": [],
      "pin_cursor": null,
      "pin_sync_state": null,
      "profile_id": "<account:Charlie Chaplin>",
      "read_message_nr": 1,
      "send_message_nr": 1,
      "show_message_nr": 1,
      "snooze_interval": 0,
      "snooze_time": 0,
      "teams": [],
      "topic": "autoManagedConvTopic",
      "topic_message_nr": 1,
      "unread_count": 0,
    },
    "stream": [
      {
        "account_id": "<account:Don Johnson>",
        "activity_time": "...",
        "dialog_id": null,
        "display_name": "Don Johnson",
        "email": "<email:Don Johnson>",
        "fleep_address": "<fladdr:Don Johnson>",
        "is_hidden_for_add": false,
        "mk_account_status": "active",
        "mk_rec_type": "contact",
        "organisation_id": null,
        "sort_rank": 0,
      },
      {
        "account_id": "<account:Mel Gibson>",
        "activity_time": "...",
        "dialog_id": null,
        "display_name": "Mel Gibson",
        "email": "<email:Mel Gibson>",
        "fleep_address": "<fladdr:Mel Gibson>",
        "is_hidden_for_add": false,
        "mk_account_status": "active",
        "mk_rec_type": "contact",
        "organisation_id": null,
        "sort_rank": 0,
      },
      {
        "admins": [
          "<account:Charlie Chaplin>",
        ],
        "autojoin_url": "<autojoin:autoManagedConvTopic>",
        "begin_message_nr": 1,
        "bw_message_nr": 1,
        "can_post": true,
        "cmail": "<cmail:autoManagedConvTopic>",
        "conversation_id": "<conv:autoManagedConvTopic>",
        "creator_id": "<account:Charlie Chaplin>",
        "default_members": [],
        "export_files": [],
        "export_progress": "1",
        "fw_message_nr": 1,
        "guests": [],
        "has_email_subject": false,
        "has_pinboard": false,
        "has_task_archive": false,
        "has_taskboard": false,
        "inbox_message_nr": 1,
        "inbox_time": "...",
        "is_automute": false,
        "is_full": true,
        "is_init": true,
        "is_list": false,
        "is_managed": true,
        "is_mark_unread": false,
        "is_premium": false,
        "is_tiny": false,
        "join_message_nr": 1,
        "label_ids": [],
        "last_inbox_nr": 0,
        "last_message_nr": 1,
        "last_message_time": "...",
        "leavers": [],
        "members": [
          "<account:Charlie Chaplin>",
          "<account:Don Johnson>",
          "<account:Mel Gibson>",
        ],
        "mk_alert_level": "default",
        "mk_conv_type": "cct_default",
        "mk_init_mode": "ic_full",
        "mk_rec_type": "conv",
        "organisation_id": "<org:autoManagedConvOrgName>",
        "passive": [],
        "pin_cursor": null,
        "pin_sync_state": null,
        "profile_id": "<account:Charlie Chaplin>",
        "read_message_nr": 1,
        "send_message_nr": 1,
        "show_message_nr": 1,
        "snooze_interval": 0,
        "snooze_time": 0,
        "teams": [],
        "topic": "autoManagedConvTopic",
        "topic_message_nr": 1,
        "unread_count": 0,
      },
      {
        "account_id": "<account:Charlie Chaplin>",
        "conversation_id": "<conv:autoManagedConvTopic>",
        "inbox_nr": 0,
        "lock_account_id": null,
        "message": {
          "members": [
            "<account:Don Johnson>",
            "<account:Mel Gibson>",
          ],
          "org_name": "autoManagedConvOrgName",
          "organisation_id": "<org:autoManagedConvOrgName>",
          "topic": "autoManagedConvTopic",
        },
        "message_nr": 1,
        "mk_message_state": "urn:fleep:message:mk_message_state:system",
        "mk_message_type": "create",
        "mk_rec_type": "message",
        "posted_time": "...",
        "prev_message_nr": 0,
        "profile_id": "<account:Charlie Chaplin>",
        "tags": [],
      },
      {
        "conversation_id": "<conv:autoManagedConvTopic>",
        "is_deleted": false,
        "mk_rec_type": "section",
        "mk_section_subtype": "urn:fleep:section:mk_section_subtype:archived",
        "mk_section_type": "urn:fleep:section:mk_section_type:task",
        "name": "Archived",
        "section_id": "<section:Archived>",
        "sync_cursor": null,
        "sync_state": null,
        "weight": 0,
      },
      {
        "conversation_id": "<conv:autoManagedConvTopic>",
        "is_deleted": false,
        "mk_rec_type": "section",
        "mk_section_subtype": "urn:fleep:section:mk_section_subtype:default",
        "mk_section_type": "urn:fleep:section:mk_section_type:task",
        "name": "To Do",
        "section_id": "<section:To Do>",
        "sync_cursor": null,
        "sync_state": null,
        "weight": 4294967296,
      },
    ],
};

test('create org and create auto managed conv in it', function () {
    let client = UC.charlie;
    let conv_topic = 'autoManagedConvTopic';
    let org_name = 'autoManagedConvOrgName';

    return thenSequence([
        // create org
        () => client.api_call("api/business/create", {organisation_name: org_name}),
        // create managed conv with team
        () => client.api_call("api/conversation/create", {
            topic: conv_topic,
            account_ids: [UC.mel.account_id, UC.don.account_id]}),
        (res) => expect(UC.clean(res)).toMatchObject(create_conv_result),
        () => client.poll_filter({mk_rec_type: 'conv', topic: conv_topic}),
    ]);
});


test('create org and create auto managed conv with team', function () {
    let client = UC.harry;
    let conv_topic = 'autoManagedTeamTopic';
    let org_name = 'autoManagedTeamOrgName';
    let org_team = 'autoManagedTeamConv';

    return thenSequence([
        // create team
        () => client.api_call("api/team/create", {
            team_name: org_team,
            account_ids: [UC.vin.account_id, UC.ron.account_id]}),
        () => client.poll_filter({mk_rec_type: 'team', team_name: org_team}),
        // create org
        () => client.api_call("api/business/create", {organisation_name: org_name}),
        // create managed conv with team
        () => client.api_call("api/conversation/create", {
            topic: conv_topic,
            team_ids: [client.getTeamId(org_team)], }),
        (res) => expect(UC.clean(res)).toMatchObject({
            "header": {
              "admins": [
                "<account:Harry Potter>",
              ],
              "autojoin_url": "<autojoin:autoManagedTeamTopic>",
              "begin_message_nr": 1,
              "bw_message_nr": 1,
              "can_post": true,
              "cmail": "<cmail:autoManagedTeamTopic>",
              "conversation_id": "<conv:autoManagedTeamTopic>",
              "creator_id": "<account:Harry Potter>",
              "default_members": [],
              "export_files": [],
              "export_progress": "1",
              "fw_message_nr": 2,
              "guests": [],
              "has_email_subject": false,
              "has_pinboard": false,
              "has_task_archive": false,
              "has_taskboard": false,
              "inbox_message_nr": 1,
              "inbox_time": "...",
              "is_automute": false,
              "is_full": true,
              "is_init": true,
              "is_list": false,
              "is_managed": true,
              "is_mark_unread": false,
              "is_premium": false,
              "is_tiny": false,
              "join_message_nr": 1,
              "last_inbox_nr": 0,
              "last_message_nr": 2,
              "last_message_time": "...",
              "leavers": [],
              "members": [
                "<account:Harry Potter>",
                "<account:Ron Viislei>",
                "<account:Vin Diisel>",
              ],
              "mk_alert_level": "default",
              "mk_conv_type": "cct_no_mail",
              "mk_init_mode": "ic_full",
              "mk_rec_type": "conv",
              "organisation_id": "<org:autoManagedTeamOrgName>",
              "passive": [],
              "pin_cursor": null,
              "pin_sync_state": null,
              "profile_id": "<account:Harry Potter>",
              "read_message_nr": 2,
              "send_message_nr": 1,
              "show_message_nr": 2,
              "snooze_interval": 0,
              "snooze_time": 0,
              "teams": [
                "<team:autoManagedTeamConv>",
              ],
              "topic": "autoManagedTeamTopic",
              "topic_message_nr": 1,
              "unread_count": 0,
            },
        }),
    ]);
});
